### ISSUE TITLE
views by folder , nested folders hiracy

### ISSUE THREAD

**Issue by zakidze** [vordgi/nimpl-inio#52]
i want to open iniio in the root foler where there is multiple locales, then it detects each key in the en side and in the de side
it knows what key  ,
also the keys are not they dont show much, so we need to change the structure of the view 
the manager main functuioality is to identify the keys that dosent have value in specifique locales mybe i added in english but i missed in german ..... so it highlight it ....

i was looking for somthing exaclty like that and with  browsing like windows  for dictionry

by the way thanks for all the eforts

what i wanted is a product exaclty like the last screenshot  + ability to modify exsisting jsons and a json browser
and also a functionality to find the keys that dont have values in certain locales ,
and when adding a key if there is duplicate it move it to common key

screenshot 3 is what happens when i open inio in (en local ) coudnet oopen it in root folder ,
the keys are not discriptive values are discriptive

by the way the same jsons are in the de and en folder but both refrence to diffrent values same keys

can you please contact me at : zakidze@gmail.com

![Capture1](https://github.com/vordgi/nimpl-inio/assets/61497110/ff5186c2-a830-42c7-9a54-9f65d919e54d)
![Capture2](https://github.com/vordgi/nimpl-inio/assets/61497110/e5d24d9e-1839-4e95-9276-2ad214088a90)

![Capture3](https://github.com/vordgi/nimpl-inio/assets/61497110/d72fc12f-01f6-4891-9406-14a716f06abb)
pl-inio/assets/61497110/4f239dff-d8c2-46d8-ae97-53510a24eae7)
![Capture4](https://github.com/vordgi/nimpl-inio/assets/61497110/79ff71f1-f7ce-4236-84bf-bd45be6ccfc1)

**Comment by vordgi** [comment]
You can run `inio` with directory as dynamic param, like `PATTERN='./<key>/header' inio`

Can you please create repo with this structure and base JSONs inside?

**Comment by zakidze** [comment]
dont really get it what you mean can you show a configuration file? 
you can see the structure of josn

**Comment by vordgi** [comment]
You can run inio without configuration file - via environment variables.

But config will looks like:

```js
module.exports = {
  pattern: './<key>/header'
}
```

**Comment by vordgi** [comment]
But I see that there is a need for the ability to switch directories (_f.e. from `header` to `footer`_) - I'll think about it

**Comment by zakidze** [comment]
my folders are like this

/en 
/dashboard
  selling.json
  about.json
homepage.json   


/de
/dashboard
  selling.json
  about.json
homepage.json  

i want when enter the inio without any config it automaticly detects this ,
mybe i just need to specify where is the de folder and where is the en folder and it does the comparion on it own

that pattern shold i just copy past it???

also i d like to have a meet with you with google meet

**Comment by vordgi** [comment]
I haven't planned yet for all possible files to be editable through the interface.

You can run `PATTERN='<key>/dashboard/selling.json'` and edit the selling translations.

I will make it possible to switch parts of the path, i.e. to click on the selling.json segment from the interface and select about.json.

**Comment by vordgi** [comment]
Shipped!

(_a little demo - https://x.com/i/status/1800229367421026489_)

I hope this is exactly what you needed!

**Comment by zakidze** [comment]
`.
/
<key>
/
checkout.json`


i suppose the key is the locales , the name of the root, locales yes this is exactly what i need
however in the UI
![Capture1](https://github.com/vordgi/nimpl-inio/assets/61497110/aeb84e93-8020-409a-963a-e91f5beddbd8)


AS you see in this pictures the keys on their self are not descriptive, 
![Untitled](https://github.com/vordgi/nimpl-inio/assets/61497110/41f2254c-7397-41c6-922d-204a5727be6f)

where the first column is the base laungauge in this case EN and the rest in the other columns , and keys are in rows

**Comment by zakidze** [comment]
i want to see that layout

**Comment by zakidze** [comment]
by the way thank you sooo much <3

**Comment by vordgi** [comment]
To be honest, I find the current interface much more convenient, but I'll plan to implement a toggle for switching to such. Could you then, please, create another task for the structure? And this one can be closed

**Comment by vordgi** [comment]
You can also star the package, it helps its growth))

**Comment by zakidze** [comment]
i willl😁😁😁
