### ISSUE TITLE
feature request: highlight missing values//keys

### ISSUE THREAD

**Issue by zakidze** [vordgi/nimpl-inio#56]
i want  this app to scan all the keys and if it dosent find a  value the key would be highlighted

eg 

lets say the key : greeting 

in english : hello 

in french : bonjour

in german : ""

as you can see in german theere is no value

i want  the key to get highlited

the same for keys

if a key exsist in local and dosent exsist in anathor one it get highlited

**Comment by vordgi** [comment]
I will tackle this issue first. Gonna add filters. And the first filter will be "missing value".

**Comment by zakidze** [comment]
yes this one very important good luck😁

**Comment by vordgi** [comment]
Shipped!

Run
```bash
npm i @nimpl/inio -g
inio
```
And edit!)

**Comment by zakidze** [comment]
works super nice

**Comment by zakidze** [comment]
looking to know whats the next issue
