### ISSUE TITLE
feature request: highlight repetitive keys and prevent adding them

### ISSUE THREAD

**Issue by zakidze** [vordgi/nimpl-inio#57]
i want  a warning or smth on repetitive keys
repetitive keys shold be in one place witch is global transation or common file or its one file

eg there is common json and home json and about json

if a key is used in about json and same key is used in home json the app sujjest to move the key to global

sujjest not move on it self only if user wanted to move

**Comment by zakidze** [comment]
call it a global filter for repitive keys across all project

**Comment by vordgi** [comment]
The problem is to detect files where inio should check for.

f.e., if Inio runs in the root dir, how can it ensure that it should checks for repetition only in the 'translates' dir, and not in 'node_modules'?

**Comment by zakidze** [comment]
a user can drag and drop the locales folder

**Comment by zakidze** [comment]
also i want if a user wants to add new key , using the dashbaord inio warns him that there alredy a keys same inside  and it shows where it located , 

so this check would be for every adding new key

**Comment by zakidze** [comment]
why not a user points into a DIR  inio scans jsons , and highlight for repititieve keys amonge the dir

**Comment by vordgi** [comment]
Because for example between some/en/header.json and some/de/header.json - repeating keys - that's all. Also with some/else/en/home/meta.json and some/else/de/home/meta.json. And how to understand which of them are planned, and which are not.

I understand that you have a clear and understandable structure, but I am thinking about a universal solution.

**Comment by zakidze** [comment]
a universal souloution is to label the jsons so inio know what to do with them, why know start with the structured jsons for now , later switch to unstructured

**Comment by vordgi** [comment]
This isnt universal, companies may have their own rules and reasons for specific naming and structure

**Comment by zakidze** [comment]
i know its a manuel work to label the jsons  but its get the job done+ 
inio saves this configuration  so its once for all 

a person will specify the name of jsons in diffrent locales      
for example

de/home.json
en/about.json

in file structre they are not same name but i can overwrite in inio make a configuration and make them that they have the same keys  so inio scans and know what to do

ps : it dosent change the file name in hardrive just we guide inio into the jsons

**Comment by zakidze** [comment]
i name a namespace named : contact 

in en version  i specify    en/home.json
in de versioon i speify   de/qsdfmkljsqdf/qsdfsdqf.json

in file system they are just some paths 
but a manuel work is required so inio knows that the namespace have 2 files in thoes dir  ( a GUI is required to help with this)
and thats it 
inio saves it configuration inside the project loccaly  and we are done

**Comment by vordgi** [comment]
Got it, thanks! I will think about this solution

**Comment by zakidze** [comment]
hope to see it come to life

**Comment by vordgi** [comment]
Shipped repetitive keys and repetitive values filters 🚀
