### ISSUE TITLE
feature request layout structure

### ISSUE THREAD

**Issue by zakidze** [vordgi/nimpl-inio#60]
i want this layout

as somon who worked alot in i18n this layout is needed its facilitate the view of the values in diffrent locales without open the accordion

![338326315-41f2254c-7397-41c6-922d-204a5727be6f (1)](https://github.com/vordgi/nimpl-inio/assets/61497110/3869ae95-7ea7-4664-a3b4-0b551bf01e49)

![338328733-22c77924-df7d-451a-bb63-65eb111c8741](https://github.com/vordgi/nimpl-inio/assets/61497110/2299e760-26cb-4895-a62f-eaee74e960af)

**Comment by vordgi** [comment]
_I gonna implement pagination and get to this one_

**Comment by zakidze** [comment]
😁😁😁😁😁😁😁😁😁😁good luck thus id my most wanted request

**Comment by zakidze** [comment]
exctly that

**Comment by vordgi** [comment]
Shipped!

**Comment by zakidze** [comment]
connngrats finnaly ::::: whats the next issue

**Comment by zakidze** [comment]
just tryed it
