### ISSUE TITLE
feature request a single page that shows all the missing values

### ISSUE THREAD

**Issue by zakidze** [vordgi/nimpl-inio#87]
i want to open inio in root locales folder it scanes all local

then it retunes a single page where it retunres all the missing value...

in all files

its like a summary of missing values

**Comment by vordgi** [comment]
You can try latest version (`npm i @nimpl/inio@0.8.3-canary.2 -g`) and test multiple pattern:
```js
module.exports = {
    experimental: {
        pattern: ["i18n/<key>/footer.json", "i18n/<key>/test.json"],
        ignore: ["i18n/wrong/footer.json"],
    },
};
```
Then just use "missings" filter

**Comment by zakidze** [comment]
i will test but  one thing shold i put the config in the root localez folder then open inio there?

**Comment by zakidze** [comment]
i liked the multi pattern its really great , it would be cool also to

configure this multi pattern in the  UI

**Comment by vordgi** [comment]
> i will test but one thing shold i put the config in the root localez folder then open inio there?

Put it where you usually run inio

> configure this multi pattern in the UI

Already in progress:

![image](https://github.com/vordgi/nimpl-inio/assets/91429106/23c056a7-311a-4e81-a49b-82eafd340689)

**Comment by zakidze** [comment]
make it  a combobox select box with checkbox

so i wont have to type each pattern they 

the jsons  appare in select box and i select what i want


now you got your way to let inio knows about structured jsons

**Comment by zakidze** [comment]
same with selecting  one pattern in the UI but with checkboxs so i can select multiple at once

**Comment by vordgi** [comment]
What if inio found hundreds of files? What if suddenly thousands? How to determine what is the "key" in these paths?

**Comment by zakidze** [comment]
then just let the user desides with checkbox

i find how i currently set the pattern is easy

like a select box and i scroll throught folders and all

however i d like to use checkboxes same UI but with checkboxses

its like a pattern bulk builder helper

**Comment by vordgi** [comment]
But how to determine what is the "key" in these paths?

**Comment by zakidze** [comment]
![Capture](https://github.com/vordgi/nimpl-inio/assets/61497110/bc2c4a83-8c21-4f1d-8d42-f75e068b6a02)



look i have alot of jsons i d like to just add checkboxes so insted of selecting 1 pattern i select all of them

**Comment by zakidze** [comment]
like this i have to switch one by one

**Comment by zakidze** [comment]
i dont want to write everything just a single select i chose with checkbox whats included and thats it

**Comment by zakidze** [comment]
you can see my list is long but i want to include all thoes jsons

also a configuration can be exported so i can use it the  next time  and that is related to 
this issue:


https://github.com/vordgi/nimpl-inio/issues/108


i want to open inio from one place and save the dir of multiple projects and also thoes pattern for multiple projects in my disk loccaly

**Comment by vordgi** [comment]
You will might to write `<key>/*.json` and it will match all your files

**Comment by zakidze** [comment]
now thats wild you shold include this to trick the docs

a checkbox to be usuful so i can select what i want not nessisarly everything 

ps i just tested the multiple pattern it work veryyyy nice

**Comment by vordgi** [comment]
Got it, thanks!

**Comment by zakidze** [comment]
by the way you shold group the jsons by their name of file  like when specifying for bulk jsons there shold be header with group of keys speicfying the file name

+

a filter to show or hide the pattern quick and fast you know just some filters

**Comment by vordgi** [comment]
What if my structure:
terms
--header
----en.json
----de.json
--footer
----en.json
----de.json

**Comment by zakidze** [comment]
donno what will be happen right there

but we shold make a config  for patterns like for unusual patterns  and point jsons mannually 

at first specify in the docs that this is the recomonded way 

and if you want somthing costum then you shold do some manuel work

**Comment by zakidze** [comment]
You will be able to write <key>/*.json and it will match all your files

i tryed this right now but it did not work so i have to type everyhting mannually

**Comment by vordgi** [comment]
It's in work tight now

**Comment by zakidze** [comment]
![Capture](https://github.com/vordgi/nimpl-inio/assets/61497110/c7661b65-874d-4c05-8bee-ae16cb4baba3)


add this to the list a header to indicate where are thoes keys else its a mess

**Comment by vordgi** [comment]
Patterns editing via UI shipped!

**Comment by zakidze** [comment]
you added the * star?

**Comment by zakidze** [comment]
u can close this issie if you want since this feature is shipped

**Comment by vordgi** [comment]
https://x.com/i/status/1808962108224385236
_Here a little demo_

**Comment by vordgi** [comment]
Thank you for your help! I will also try to think about an implementation for checkboxes.

**Comment by zakidze** [comment]
i shold be included as a co fouder as alot of ideas are mine including the start of this project🤣😅😆

**Comment by zakidze** [comment]
well : a thank you to you too like honestly arriving to this point i know its alot of hard work


its pleasure to see this project going so thank you

**Comment by vordgi** [comment]
To be honest, part of this functionality already existed, as I have a lot of work with translations at job (10 regions and dozens of services 😬). I needed a reason to bring all this together into a full-fledged service. And thank you for this reason!) 🚀

I hope this will be a project that brings benefits, rather than leading to my burnout 😁

**Comment by zakidze** [comment]
now whats next?

**Comment by vordgi** [comment]
Relax) Then think about some personal ideas. _Maybe I'll work at #61_

**Comment by zakidze** [comment]
you know  best goodluck

i recomond starting with the duplicates issue as its more important

load jsons thought multiple patterns

select a common json

and show duplicates of the common json and sujjest to move them
